config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'sheets#index'
  resources :sheets do
    collection do
            get  :notes
            get  :logs
    end
    member do
      get  :note
      get  :lines
      get  :line
      get  :get_image
      get  :detail
      get  :json_download
      post :new_line
      post :new_note
      post :new_image
      post :move_note
      post :edit_note
      post :divide_note
      post :resize_note
      post :move_z_note
      post :delete_note
      post :delete_line
      post :add_sheet
      post :json_upload
      post :unite_note
      post :ununite_note
    end
    
  end
  

end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  belongs_to :user
  has_many :notes,:dependent => :destroy
  has_many :lines,:dependent => :destroy
  has_many :logs,:dependent => :destroy
  accepts_nested_attributes_for :notes

end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: [:show,:edit,:update, :destroy,:detail]

  respond_to :html

  before_filter :authenticate_user!

    # GET /sheets
    # GET /sheets.json
    def index
      @sheets = current_user.sheets.all
      if @sheets.empty?
        first_sheet
        @sheets = current_user.sheets.all
      end
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @sheets }
      end
    end
    # GET /sheets/1
    # GET /sheets/1.json
    def show

      if @sheet.user_id == current_user.id or current_user.id == 1
        @notes = @sheet.notes.sort_by{|n|n.note_num}
        @notes.map{|note|
          note.body.gsub(/<\/*div>/,"")
          note.body.gsub(/<br clear="none">/,"/n")
        }

        respond_to do |format|
          format.html # show.html.erb
          format.json { render :json  => @notes }

        end
      else
        redirect_to sheets_path,:alert => "access denied"
      end
    end

    def detail
      @notes = @sheet.notes
      respond_to do |format|
        format.html 
        format.json { render :json  => @notes }
      end
    end
    # GET /sheets/new
    # GET /sheets/new.json
    def new
      @sheet = Sheet.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json  => @sheet }
      end
    end

    # GET /sheets/1/edit

    def edit

    end

    # POST /sheets
    # POST /sheets.json
    def create
      @sheet = Sheet.new(sheet_params)
      user = User.find(current_user)

      respond_to do |format|
        if user.sheets << @sheet
          log = Log.new(:text => "create sheet #{@sheet.title}")
          @sheet.logs << log
          format.html { redirect_to @sheet}
          format.json { render :json => @sheet, :status => :created, :location => @sheet }
        else
          format.html { render :action => "new" }
          format.json { render :json => @sheet.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /sheets/1
    # PUT /sheets/1.json
    def update
       if @sheet.user_id = current_user.id
        respond_to do |format|
          if @sheet.update(sheet_params)
            format.html { redirect_to @sheet, :notice => 'Sheet was successfully updated.' }
            format.json { head :ok }
          else
            format.html { render :action => "edit" }
            format.json { render :json =>  @sheet.errors, :status => :unprocessable_entity }
          end
        end
      else
        redirect_to sheets_path,:alert => "access denied"
      end
    end

    # DELETE /sheets/1
    # DELETE /sheets/1.json
    def destroy
      if @sheet.user_id == current_user.id
        @sheet.destroy

        respond_to do |format|
          format.html { redirect_to sheets_url }
          format.json { head :ok }
        end
      else
        redirect_to sheets_path,:alert => "access denied"
      end

    end


    def notes 
      @sheet = Sheet.find(params[:sheet_id])
      @notes = @sheet.notes
      respond_to do |format|
        format.json { render :json  => @notes }
       end
    end

    def note
      @note = Note.where(:sheet_id => params[:sheet_id].to_i).where(:note_num => params[:note_id].to_i).first
      respond_to do |format|
       format.json { render :json  => @note }
      end
    end

    def new_note
      @sheet = Sheet.find(params[:id])
            @note = Note.new({
              :title    => "新しいノート",
              :note_num => params[:last].to_i + 1,
              :body     => "新しいノート",
              :height   => 70,
              :x        => params[:x],
              :y        => params[:y],
              :color    => params[:font],
              :bg_color => params[:bg]
              })
      log = Log.new({
        :text => "create note #{@note.note_num},title:#{@note.title},body:#{@note.body},x:#{@note.x},y:#{@note.y},color:#{@note.color},bg_color:#{@note.bg_color}"
      })
      @sheet.logs << log
      @sheet.notes << @note
      @sheet.save
      head(200)
    end

    def new_line
      @sheet = Sheet.find(params[:id])
      line = Line.new({
        :title => params[:line_id],
        :note_id => params[:note1].to_i,
        :connected_id => params[:note2].to_i
      })
      log = Log.new({:text => "create line #{line.id},note_id:#{line.note_id},connected_id:#{line.connected_id}"})
      @sheet.logs << log
      @sheet.lines << line

      head(200)

    end

    def lines
      @sheet = Sheet.find(params[:id])
      @lines = @sheet.lines
      respond_to  do |format|
        format.json {render :json => @lines}
      end
    end

    def line
      id = params[:line_id].to_i
      @lines = Line.where("note_id = ? or connected_id = ?",id,id)
      respond_to do |format|
        format.json{render :json => @lines}
      end
    end

    def delete_line
      @line = Line.where({:sheet_id => params[:sheet_id],:title => params[:line_id]}).first
      @sheet = Sheet.find(params[:sheet_id])
      log = Log.new({:text => "delete line #{@line.id}"})
      @sheet.logs << log
      @line.destroy
      head(200)
    end

    def divide_note
      @sheet = Sheet.find(params[:sheet_id])
      @note = Note.where(:sheet_id => params[:sheet_id].to_i).where(:note_num => params[:note_id].to_i).first
      log = Log.new({:text => "divide note #{@note.id}"})
      @sheet.logs << log
      det = '<br clear="none">' * params[:line].to_i
      notes = @note.body.split(det)
      i = 1
      notes.each do |note|
        @sheet.notes << Note.new({
            :title => @note.title+i.to_s,
            :note_num => params[:last].to_i + i,
            :body => note,
            :x => params[:x].to_i + i*10,
            :y => params[:y].to_i + i*10,
            :z => params[:z].to_i + 5
        })
        i +=1
      end
     @sheet.save
     head(200)
    end

    def move_note
      sheet = Sheet.find(params[:sheet_id].to_i)
      note = Note.where(:sheet_id => params[:sheet_id].to_i).where(:note_num => params[:note_id].to_i).first

      log = Log.new({:text => "move notea #{note.id},from #{note.x},#{note.y},to #{params["x"]},#{params["y"]}"})
      sheet.logs << log
      note.update_attributes({
        :x => params["x"].to_i,
        :y => params["y"].to_i
        }
      )
      head(200)
    end

    def move_z_note
      sheet = Sheet.find(params[:sheet_id].to_i)
      note = Note.where(:sheet_id => params[:sheet_id].to_i).where(:note_num => params[:note_id].to_i).first
      if params["z"] == "up"
        note.z = note.z+1
      elsif params["z"] == "down"
        note.z = note.z-1 unless note.z == 0
      end
      log = Log.new({:text => "note #{note.id} #{params["z"]}"})
      sheet.logs << log
      note.save
      head(200)
    end

    def resize_note
      sheet = Sheet.find(params[:sheet_id].to_i)
      note = Note.where(:sheet_id => params[:sheet_id].to_i).where(:note_num => params[:note_id].to_i).first
      log = Log.new({:text => "resize note #{note.id},from #{note.width} #{note.height},to #{params[:width]} #{params[:height]}" })
      sheet.logs << log
      if params[:image]
        body = Nokogiri::HTML(note.body).children.children.children
        body.css("img").attribute("width").value = "#{params[:width]}"
        body.css("img").attribute("height").value = "#{params[:height].to_i - 30}"
        note.update_attributes({
          :width => params["width"],
          :height => params["height"],
          :body => body.to_html
          }
        )

      else  
        note.update_attributes({
          :width => params["width"],
          :height => params["height"]
          }
        )
      end
      head(200)
    end

    def edit_note
      @sheet = Sheet.find(params[:sheet_id])
      @note = Note.where(:sheet_id => params[:sheet_id].to_i).where(:note_num => params[:note_id].to_i).first
      if(params[:mode] == "edit")
        @note.update_attributes(
          {
            :title => params[:note_title],
            :body => params[:note_body],
            :color => params[:font_color],
            :bg_color => params[:background_color],
            :font_size => params[:font_size],
            :text_align => params[:text_align]
          }
        )
        log = Log.new({
          :text => "edit note #{@note.id},title:#{@note.title},body:#{@note.body},x:#{@note.x},y:#{@note.y},color:#{@note.color},bg_color:#{@note.bg_color}"
        })
        @sheet.logs << log

        head(200)
      else
        @note.update_attributes(:body => params[:note_body])
        log = Log.new({
          :text => "edit note #{@note.id},title:#{@note.title},body:#{@note.body},x:#{@note.x},y:#{@note.y},color:#{@note.color},bg_color:#{@note.bg_color}"
        })
        @sheet.logs << log
        head(200)
      end 
    end

    def delete_note
      sheet = Sheet.find(params[:sheet_id])
      id = params[:note_id]
      note = Note.where(:sheet_id => params[:sheet_id]).where(:note_num => params[:note_id].to_i).first
      log = Log.new({:text => "delete note #{note.id}"})
      sheet.logs << log
      line = Line.where("note_id = ? or connected_id = ?",id,id)
      line.each{|l|l.destroy}
      note.destroy
      head(200)
    end

    def unite_note
      sheet = Sheet.find(params[:sheet_id])
      note = Note.where(:sheet_id => params[:sheet_id],:note_num => params[:note_id]).first
      params[:u_notes].each do |note_id|
        unote  = Note.where(:sheet_id => params[:sheet_id],:note_num => note_id).update_all(:united_num => note.note_num)
      end
      note.update_attribute(:unite_flag,true)
      head(200)
    end

    def ununite_note
      sheet = Sheet.find(params[:sheet_id])
      note = Note.where(:sheet_id => params[:sheet_id],:note_num => params[:note_id]).first
      note.update_attribute(:unite_flag,false)
      unote  = Note.where(:sheet_id => params[:sheet_id],:united_num => note.note_num).update_all(:united_num => 0)

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_form.html.erb
<%= form_for(@sheet) do |f| %>
  <% if @sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sheet.errors.count, "error") %> prohibited this sheet from being saved:</h2>

      <ul>
      <% @sheet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sheets/_notes.html.erb
<% notes.each do |note| %>
	<div class="note" id="note<%= note.note_num -%>" >
   		<article id="text<%= note.note_num -%>"class="text">
			<%=raw note.body if note.body %>
		</article>
		<p class="title" ><%= note.title %></p>
	</div>
<% end%>

app/views/sheets/detail.html.erb
<%= javascript_include_tag("detail")%>
<div class="show">
<header >
  <h2 class="viconote">ViCoNote:<%= @sheet.title %></h2>
  <div class="title" id="sheet<%= @sheet.id -%>"></div>  
</header>

<nav>
	<ul>
		<li>Menu </li>
		<li><%= button_to 'Back', sheets_path,:class => "button",:method => "get"%></li>
		<li><button id="start">Start</button></li>
		<li><button id="next">Next</button></li>
	</ul>
</nav>

<div id="main">
	<div id="map">
		<% @notes.each do |note|%>
			<div class="mnote" id="mnote<%= note.note_num -%>" >
			</div>
		<%end%>
		<div id="map-view">	</div>
	</div>
	<button id="map-hidden">-</button>
	<div id="sheet" class="canvas">
		<div id="paper-div"></div>
   		<%= render "notes",:notes => @notes %>
	</div>

</div>
<div id="authenticity_token"><%= form_authenticity_token %></div>
</div>
</div>

app/views/sheets/edit.html.erb
<h1>Editing sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sheet %> |
<%= link_to 'Back', sheets_path %>

app/views/sheets/index.html.erb
<%= javascript_include_tag("sheets")%>
<div class="show">
<header>
  <h2 class="viconote">ViCoNote</h2>
</header>
<nav>
	<%= link_to 'New Sheet', new_sheet_path %>
	<span class="logout">
		<% if user_signed_in? %>
		  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
		<% end %>
	</span>

</nav>
<article class="index-main">
<% @sheets.each do |sheet| %>
	<div class="index-sheet" id="sheet<%= sheet.id%>">
		<%= sheet.title%>
		<ul class="enote_ul">
			<li class="enote_li"><%= link_to 'Show', sheet %></li>	
			<li class="enote_li"><%= link_to 'Edit', edit_sheet_path(sheet) %></li>
			<li class="enote_li"><%= link_to 'Destroy', sheet, :confirm => 'Are you sure?', :method => :delete %></li>	
		</ul>
		<br>
		<div class="map" id="map<%= sheet.id -%>">
			<% sheet.notes.each do |note|%>
				<div class="mnote" id="snote<%=sheet.id-%><%=note.note_num -%>" >
				</div>
			<%end%>	
		</div>
	</div>
<%end%>
</article>

</div>

app/views/sheets/json_upload.html.erb
<%= @content %>
<br>
<%= @jsons.each do |json| %>
	<%=  json %><br>
<%  end %>

app/views/sheets/new.html.erb
<h1>New sheet</h1>

<%= render 'form' %>

<%= link_to 'Back', sheets_path %>

app/views/sheets/show.html.erb
<%= javascript_include_tag("sheets")%>
<div class="show">
<header >
  <h2 class="viconote">ViCoNote:<%= @sheet.title %></h2>
  <div class="title" id="sheet<%= @sheet.id -%>"></div>  
</header>

<nav>
	<ul>
		<li>Menu </li>
		<li><%= button_to 'Back', sheets_path,:class => "button",:method => "get"%></li>
		<li><button id="json_upload" class="button">ファイル取り込み</button></li>
		<li><%= button_to "データファイルダウンロード",{:action => "json_download",:id=> @sheet.id},:class => "button",:method => "get"%></li>
		<li class="logout">
			<% if user_signed_in? %>
			  <%= button_to "Sign out",destroy_user_session_path,:method => :delete,:class => "button"%>
			<% end %>
		</li>
	</ul>
	<div id="upload">
		<%= form_tag({:controller=>"sheets",:action=>"json_upload"},{:multipart => true}) do %>
			<%= hidden_field_tag :sheet_id,@sheet.id%>
			<%= file_field_tag "f",:accept => 'application/json' %>
			<%= submit_tag("保存")%>
		<% end %>
	</div>
</nav>


<div id="main">
	<div id="map">
		<% @notes.each do |note|%>
			<div class="mnote" id="mnote<%= note.note_num -%>" >
			</div>
		<%end%>
		<div id="map-view">	</div>
	</div>
	<button id="map-hidden">-</button>
	<div id="sheet" class="canvas">
		<div id="paper-div"></div>
   		<%= render "notes",:notes => @notes %>
	</div>
	<div id="dialog" class="edit">
		<%= hidden_field_tag "note_id"%>
		<%= hidden_field_tag "sheet_id",@sheet.id%>
		<%= hidden_field_tag "mode","edit"%>
		<div class="field">
			<table border="0" cellspacing="5" cellpadding="5">
				<tr>
					<th><%= label_tag "Title"%></th>
					<th><%= label_tag "Background Color"%></th>
					<th><%= label_tag "Font Size"%></th>
					<th><%= label_tag "Font Color"%></th>
					<th><%= label_tag "Text Align"%></th>	
				</tr>
				<tr>
					<td><%= text_field_tag "note_title"%></td>
					<td><%= text_field_tag "background_color"%></td>
					<td><%= text_field_tag "font_size" %></td>
					<td><%= text_field_tag "font_color"%></td>
					<td><%= text_field_tag "text_align"%></td>
				</tr>
			</table>
		</div>

		<div class="field">
			<%= label_tag "body"%><br>
			<%= text_area_tag "note_body",nil,:rows => 5, :cols => 100 ,:class => "note_body"%>
		</div>

	</div>
</div>
<div id="authenticity_token"><%= form_authenticity_token %></div>
</div>
</div>